services:
  autogenstudio:
    image: autogenstudio-docker:latest
    container_name: autogenstudio
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8180:80"
    volumes:
      - ./config:/config
